sudo: false

language: cpp

matrix:
  include:
    - os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - binutils-gold
      - python
      - gcc-6
      - g++-6

before_script:
- git config --global user.email "ani07nov@gmail.com"
- git config --global user.name "Anirudha Bose"

- |
  export TMPDIR=/tmp
  mkdir -pv $TMPDIR/cmake

  if [ $TRAVIS_OS_NAME == 'linux' ]; then
    export CMAKE=$TMPDIR/cmake/bin/cmake
    CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.0-Linux-x86_64.tar.gz"
    travis_retry wget --no-check-certificate -O - $CMAKE_URL | tar --strip-components=1 -xz -C $TMPDIR/cmake

    export CC=/usr/bin/gcc-6
    export CXX=/usr/bin/g++-6
  fi

- $CMAKE --version
- $CC --version
- $CXX --version

script:
- |
  if [ -z $TRAVIS_TAG ]; then
    tools/packaging/cpt.py --current-dev=tar --with-cling-url=https://github.com/vgvassilev/cling
  else
    tools/packaging/cpt.py --last-stable=tar --with-cling-url=https://github.com/vgvassilev/cling
  fi

notifications:
  recipients:
  - ani07nov@gmail.com
  email:
    on_success: change
    on_failure: always
  template:
  - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

before_deploy:
- export RELEASE_TARBALL=$(ls $HOME/ci/build/cling*.tar.bz2)
- echo "Deploying $RELEASE_TARBALL to GitHub releases"

deploy:
  provider: releases
  skip_cleanup: true
  user: onyb
  password:
    secure: keCA3zXSU+58XUANasdgrDdhj4j8I2tcK747z89O1VHBYj6rbi5Pwc8VRG2LQPhHr/SC4nbX2ZEjZZUgyTKDsGrxDB+MMaDEbJyur+Np0SX0B5/r92+mi1m/404GbGfxsWFlJtaB8EzD0y2NqeSBIwU9SXVuCP1K+i3QnyK6zjozEX4rR+8GWxMXrTrtHfR+vmLvYWrKyT+zpECYIdRbrab9cOsrf0Cn/nrEPEkGKuRS9f4SRKECTAuY2x1t6njgrQK4CadonEETBJmq/c8gtNo9CVIRyYPa1R4L7Ssy0ksHaDnPLX/MHtpqyEVpdMMyjOQEDHlxIhSWWmSaFpXE2ATYJkbHbrVch6lzNGMKNUuL4PUf4qIiHFUSYyuNhhxtVQjplMs+eqMuyTAyd+sAUmYJ2m0yPFtdgmbnfG4rj7GBBMkKew0hBOx+A77Qb+9JuaXylUoMU2JO5usA5gIZIGXg+ZQH0eSG3Yb8WBSprawZLHWp9IwqBjJhOw873n1+cGjVwkbVLSTWK7EvgjKmh84aT1SfJ8cTNdj4xmkYQlvvON0RaDi7cMMcsbkxpUtY4y7ygCDyW0eznE96RDl/RITR1suOAJczE3WkQEtYEEnyVeWwWeHDX6Ir8pydaFM+M9Zk05eaDJKrHPqCzQ9qSmNhrZE+NC9fR8rsO4kBEzI=
  file: '${RELEASE_TARBALL}'
  on:
    tags: true
    repo: onyb/cling
